
SET STATISTICS IO ON
SET STATISTICS TIME ON

DECLARE @SQLString nvarchar(4000);  
DECLARE @SQLParamInfo nvarchar(4000);



SET @SQLParamInfo = N'@P1 nvarchar(21),@P2 int';

SET @SQLString = N'SELECT T1.ITEMID, T1.RECID 
FROM INVENTTABLE T1 
WHERE (((PARTITION=5637144576) AND (DATAAREAID=N''aaa'')) AND ((ITEMGROUPID=@P1) AND (ITEMFIELD=@P2)))';

exec sp_executesql @SQLString, @SQLParamInfo, @P1 = '', @P2 = 0


SET STATISTICS IO OFF
SET STATISTICS TIME OFF
